create or replace PROCEDURE SP_PORTAL_DETAIL
(
	I_HARBOUR_NUMBER IN VARCHAR2,
	O_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
	OPEN O_CURSOR FOR
	SELECT
		RQI_RQBK_NUM HARBOUR_NUMBER,
		RQSC_RQBK_ID BOOKING_ID,
		DECODE(RQSC_SH_ID, NULL, RQSC_SH_NAME, SHIPPER.CO_NAME) SHIPPER_NAME,
		DECODE(RQSC_CS_ID, NULL, RQSC_CS_NAME, CONSIGNEE.CO_NAME) CONSIGNEE_NAME,
		RQI_DATE_REQUESTED REQUEST_DATE,
		DECODE(DECODE(RQSC_POR_TYPE, 2, RQSC_POR_AIR,RQSC_POR), NULL, RQSC_POR_NAME, DECODE(RQSC_POR_TYPE, 2, PORAIR.AP_CODE, PORCITY.CT_DESC || DECODE(PORSTATES.STATE_CODE, NULL, ', ', ', ' || PORSTATES.STATE_CODE || ', ') || PORCOUNTRY.CY_CODE)) PLACE_OF_RECEIPT,
		DECODE(DECODE(RQSC_POD_TYPE, 2, RQSC_POD_AIR,RQSC_POD), NULL, RQSC_POD_NAME, DECODE(RQSC_POD_TYPE, 2, PODAIR.AP_CODE, PODCITY.CT_DESC || DECODE(PODSTATES.STATE_CODE, NULL, ', ', ', ' || PODSTATES.STATE_CODE || ', ') || PODCOUNTRY.CY_CODE)) PLACE_OF_DELIVERY,
		INCO_CODE INCOTERM,
		initcap(RQM_COMM_NAME) COMMODITY_NAME,
		HPT_HAZARDOUS HAZARDOUS,
		RQI_RQBK_TYPE TRANSPORT_TYPE,
		RQI_FCL_LCL OCEAN_CONTAINER_TYPE	-- ToDo: Use ReturnFCLContainerTypes function
	FROM
		RQBK_IDX,
		RQBK_SH_CS,
		RQBK_FEES,
		INCOTERMS,
		RQBK_MC,
		HAZARD_PERISH_TYPES,
		CITY PORCITY,
		CITY PODCITY,
		STATES PORSTATES,
		STATES PODSTATES,
		COUNTRY PORCOUNTRY,
		COUNTRY PODCOUNTRY,
		AIRPORTS PORAIR,
		AIRPORTS PODAIR,
		COMPANY SHIPPER,
		COMPANY CONSIGNEE
	WHERE RQI_RQBK_NUM = I_HARBOUR_NUMBER
		AND RQI_RQBK_ID = RQSC_RQBK_ID (+)
		AND RQI_RQBK_ID = RQF_RQBK_ID (+)
		AND RQF_INCO_CODE = INCO_ID (+)
		AND RQI_RQBK_ID = RQM_RQBK_ID (+)
		AND RQM_HAZ_PERISH = HPT_ID (+)
		AND RQSC_POR = PORCITY.CT_ID (+)
		AND PORCITY.CT_STATE_ID = PORSTATES.STATE_ID (+)
		AND PORCITY.CT_COUNTRY_ID = PORCOUNTRY.CY_ID (+)
		AND RQSC_POD = PODCITY.CT_ID (+)
		AND PODCITY.CT_STATE_ID = PODSTATES.STATE_ID (+)
		AND PODCITY.CT_COUNTRY_ID = PODCOUNTRY.CY_ID (+)
		AND RQSC_POR_AIR = PORAIR.AP_ID (+)
		AND RQSC_POD_AIR = PODAIR.AP_ID (+)
		AND RQSC_SH_ID = SHIPPER.CO_ID (+)
		AND RQSC_CS_ID = CONSIGNEE.CO_ID (+);
	EXCEPTION WHEN OTHERS THEN
		RAISE;
END;