create or replace PROCEDURE SP_PORTAL_EVENTS_OCEAN
(
  I_HARBOUR_NUMBER IN VARCHAR2,  
  O_CURSOR OUT SYS_REFCURSOR
)
AS

  V_BOOKING_ID NUMBER;

BEGIN
	SELECT RQI_RQBK_ID INTO V_BOOKING_ID   
	FROM RQBK_IDX    
	WHERE RQI_RQBK_NUM = I_HARBOUR_NUMBER;   

  OPEN O_CURSOR FOR

	SELECT 
    DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_FCL_HDR.RQFH_CONT_NUM, 'LCL') CONTAINER_NUMBER,   
		VESSELS.VS_NAME VESSEL_NAME,   
		RQBK_OC_CARRIER.RQOC_VOYAGE VOYAGE_NUMBER,   
		'Arrived Terminal: ' || CITY.CT_DESC || ', ' || DECODE(STATES.STATE_NAME, NULL, '', STATES.STATE_NAME || ', ') || COUNTRY.CY_CODE EVENT_DESCRIPTION,   
		RQBK_OC_CARRIER.RQOC_TERM_CUTOFF EXPECTED_DATE_1,   
		DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_FCL_HDR.RQFH_ARR_TERM, RQBK_LCL_HDR.RQLH_ARR_TERM) ACTUAL_DATE,   
		RQBK_IDX.RQI_RQBK_ID BOOKING_ID,   
		RQBK_OC_CARRIER.RQOC_TERM_CUTOFF EXPECTED_DATE_2   
	FROM 
    RQBK_FCL_HDR,   
		RQBK_LCL_HDR,   
		RQBK_IDX,   
		RQBK_MC,   
		RQBK_OC_CARRIER,   
		CITY,   
		STATES,   
		COUNTRY,   
		VESSELS,   
		CONT_ADDRESSES   
	WHERE RQBK_IDX.RQI_RQBK_ID = RQBK_FCL_HDR.RQFH_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_OC_CARRIER.RQOC_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_MC.RQM_RQBK_ID   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_LCL_HDR.RQLH_RQBK_ID (+)   
		AND RQBK_OC_CARRIER.RQOC_DROPOFF = CONT_ADDRESSES.CA_ADDR_ID (+)   
		AND CITY.CT_ID = DECODE(CA_TERMINAL_CITY, NULL, RQBK_MC.RQM_POR, CA_TERMINAL_CITY)   
		AND CITY.CT_STATE_ID = STATES.STATE_ID (+)   
		AND CITY.CT_COUNTRY_ID = COUNTRY.CY_ID   
		AND RQBK_OC_CARRIER.RQOC_VS_NAME = VESSELS.VS_ID   
		AND RQBK_IDX.RQI_RQBK_ID = V_BOOKING_ID   
		AND NOT (RQBK_MC.RQM_POR_TYPE = 4 AND RQBK_MC.RQM_POD_TYPE = 4) 
		AND RQBK_OC_CARRIER.RQOC_TERM_CUTOFF IS NOT NULL

	UNION

	SELECT 
    DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_FCL_HDR.RQFH_CONT_NUM, 'LCL') CONTAINER_NUMBER,   
		VESSELS.VS_NAME VESSEL_NAME,   
		RQBK_OC_CARRIER.RQOC_VOYAGE VOYAGE_NUMBER,   
		'Departed Terminal: ' || CITY.CT_DESC || ', ' || DECODE(STATES.STATE_NAME, NULL, '', STATES.STATE_NAME || ', ') || COUNTRY.CY_CODE EVENT_DESCRIPTION,   
		DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_OC_CARRIER.RQOC_TERM_CUTOFF + 1, RQBK_OC_CARRIER.RQOC_TERM_CUTOFF + 3) EXPECTED_DATE_1,   
		DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_FCL_HDR.RQFH_DPT_TERM, RQBK_LCL_HDR.RQLH_DPT_TERM) ACTUAL_DATE,   
		RQBK_IDX.RQI_RQBK_ID BOOKING_ID,   
		DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_OC_CARRIER.RQOC_TERM_CUTOFF + 1, RQBK_OC_CARRIER.RQOC_TERM_CUTOFF + 3) EXPECTED_DATE_2        
	FROM 
    RQBK_FCL_HDR,   
		RQBK_LCL_HDR,   
		RQBK_IDX,   
		RQBK_OC_CARRIER,   
		RQBK_MC,   
		CITY,   
		STATES,   
		COUNTRY,   
		VESSELS,   
		CONT_ADDRESSES   
	WHERE RQBK_IDX.RQI_RQBK_ID = RQBK_FCL_HDR.RQFH_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_OC_CARRIER.RQOC_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_MC.RQM_RQBK_ID   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_LCL_HDR.RQLH_RQBK_ID (+)   
		AND RQBK_OC_CARRIER.RQOC_DROPOFF = CONT_ADDRESSES.CA_ADDR_ID (+)   
		AND CITY.CT_ID = DECODE(CA_TERMINAL_CITY, NULL, RQBK_MC.RQM_POR, CA_TERMINAL_CITY)
		AND CITY.CT_STATE_ID = STATES.STATE_ID (+)   
		AND CITY.CT_COUNTRY_ID = COUNTRY.CY_ID   
		AND RQBK_OC_CARRIER.RQOC_VS_NAME = VESSELS.VS_ID   
		AND RQBK_IDX.RQI_RQBK_ID = V_BOOKING_ID   
		AND RQBK_IDX.RQI_FCL_LCL = 2 --LCL   
		AND RQBK_OC_CARRIER.RQOC_SAIL_DATE - RQBK_OC_CARRIER.RQOC_TERM_CUTOFF > 3
		AND NOT (RQBK_MC.RQM_POR_TYPE = 4 AND RQBK_MC.RQM_POD_TYPE = 4)
		AND RQBK_OC_CARRIER.RQOC_TERM_CUTOFF IS NOT NULL

	UNION

	SELECT 
    DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_FCL_HDR.RQFH_CONT_NUM, 'LCL') CONTAINER_NUMBER,   
		VESSELS.VS_NAME VESSEL_NAME,   
		RQBK_OC_CARRIER.RQOC_VOYAGE VOYAGE_NUMBER, 
		'Departed Terminal: ' || CITY.CT_DESC || ', ' || DECODE(STATES.STATE_NAME, NULL, '', STATES.STATE_NAME || ', ') || COUNTRY.CY_CODE EVENT_DESCRIPTION,   
		DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_OC_CARRIER.RQOC_TERM_CUTOFF + 1, RQBK_OC_CARRIER.RQOC_TERM_CUTOFF + 3) EXPECTED_DATE_1,   
		DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_FCL_HDR.RQFH_DPT_TERM, RQBK_LCL_HDR.RQLH_DPT_TERM) ACTUAL_DATE,   
		RQBK_IDX.RQI_RQBK_ID BOOKING_ID,   
		DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_OC_CARRIER.RQOC_TERM_CUTOFF + 1, RQBK_OC_CARRIER.RQOC_TERM_CUTOFF + 3) EXPECTED_DATE_2        
	FROM 
    RQBK_FCL_HDR,   
		RQBK_LCL_HDR,   
		RQBK_IDX,   
		RQBK_OC_CARRIER,   
		RQBK_MC,   
		CITY,   
		STATES,   
		COUNTRY,   
		VESSELS,   
		CONT_ADDRESSES   
	WHERE RQBK_IDX.RQI_RQBK_ID = RQBK_FCL_HDR.RQFH_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_OC_CARRIER.RQOC_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_MC.RQM_RQBK_ID   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_LCL_HDR.RQLH_RQBK_ID (+)   
		AND RQBK_OC_CARRIER.RQOC_DROPOFF = CONT_ADDRESSES.CA_ADDR_ID (+)   
		AND CITY.CT_ID = DECODE(CA_TERMINAL_CITY, NULL, RQBK_MC.RQM_POR, CA_TERMINAL_CITY)
		AND CITY.CT_STATE_ID = STATES.STATE_ID (+)   
		AND CITY.CT_COUNTRY_ID = COUNTRY.CY_ID   
		AND RQBK_OC_CARRIER.RQOC_VS_NAME = VESSELS.VS_ID   
		AND RQBK_IDX.RQI_RQBK_ID = V_BOOKING_ID   
		AND RQBK_IDX.RQI_FCL_LCL = 1 --FCL   
		AND NOT (RQBK_MC.RQM_POR_TYPE = 4 AND RQBK_MC.RQM_POD_TYPE = 4) 
		AND RQBK_OC_CARRIER.RQOC_TERM_CUTOFF IS NOT NULL 

	UNION

	SELECT 
    DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_FCL_HDR.RQFH_CONT_NUM, 'LCL') CONTAINER_NUMBER, 
		VESSELS.VS_NAME VESSEL_NAME,   
		RQBK_OC_CARRIER.RQOC_VOYAGE VOYAGE_NUMBER,   
		'Sailed: ' || CITY.CT_DESC || ', ' || DECODE(STATES.STATE_NAME, NULL, '', STATES.STATE_NAME || ', ') || COUNTRY.CY_CODE EVENT_DESCRIPTION,   
		RQBK_OC_CARRIER.RQOC_SAIL_DATE EXPECTED_DATE_1,   
		RQBK_OC_CARRIER.RQOC_ACT_SAIL_DATE ACTUAL_DATE,   
		RQBK_IDX.RQI_RQBK_ID BOOKING_ID,   
		RQBK_OC_CARRIER.RQOC_SAIL_DATE EXPECTED_DATE_2
	FROM 
    RQBK_FCL_HDR,   
		RQBK_IDX,   
		RQBK_OC_CARRIER,   
		RQBK_MC,   
		CITY,   
		STATES,   
		COUNTRY,   
		VESSELS   
	WHERE RQBK_IDX.RQI_RQBK_ID = RQBK_FCL_HDR.RQFH_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_OC_CARRIER.RQOC_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_MC.RQM_RQBK_ID   
		AND RQBK_MC.RQM_PORT_EXPORT = CITY.CT_ID   
		AND CITY.CT_STATE_ID = STATES.STATE_ID (+)   
		AND CITY.CT_COUNTRY_ID = COUNTRY.CY_ID   
		AND RQBK_OC_CARRIER.RQOC_VS_NAME = VESSELS.VS_ID
		AND RQBK_IDX.RQI_RQBK_ID = V_BOOKING_ID

	UNION

	SELECT 
    DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_FCL_HDR.RQFH_CONT_NUM, 'LCL') CONTAINER_NUMBER,   
		VESSELS.VS_NAME VESSEL_NAME,   
		RQBK_OC_CARRIER.RQOC_VOYAGE VOYAGE_NUMBER,   
		'Trans. Sailed: ' || CITY.CT_DESC || ', ' || DECODE(STATES.STATE_NAME, NULL, '', STATES.STATE_NAME || ', ') || COUNTRY.CY_CODE EVENT_DESCRIPTION,   
		RQBK_OC_CARRIER.RQOC_TRANS_SAIL_DATE EXPECTED_DATE_1,   
		RQBK_OC_CARRIER.RQOC_ACT_TRANS_SAIL_ARR_DATE ACTUAL_DATE,   
		RQBK_IDX.RQI_RQBK_ID BOOKING_ID,   
		RQBK_OC_CARRIER.RQOC_TRANS_SAIL_DATE EXPECTED_DATE_2
	FROM 
    RQBK_FCL_HDR,   
		RQBK_IDX,   
		RQBK_OC_CARRIER,   
		RQBK_MC,   
		CITY,   
		STATES,   
		COUNTRY,   
		VESSELS   
	WHERE RQBK_IDX.RQI_RQBK_ID = RQBK_FCL_HDR.RQFH_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_OC_CARRIER.RQOC_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_MC.RQM_RQBK_ID   
		AND RQBK_OC_CARRIER.RQOC_PLACE_TRANS = CITY.CT_ID   
		AND CITY.CT_STATE_ID = STATES.STATE_ID (+)   
		AND CITY.CT_COUNTRY_ID = COUNTRY.CY_ID   
		AND RQBK_OC_CARRIER.RQOC_VS_NAME = VESSELS.VS_ID
		AND RQBK_IDX.RQI_RQBK_ID = V_BOOKING_ID

	UNION

	SELECT 
    DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_FCL_HDR.RQFH_CONT_NUM, 'LCL') CONTAINER_NUMBER,   
		VESSELS.VS_NAME VESSEL_NAME,   
		RQBK_OC_CARRIER.RQOC_VOYAGE VOYAGE_NUMBER,   
		'Arrived at Port of Loading: ' || CITY.CT_DESC || ', ' || DECODE(STATES.STATE_NAME, NULL, '', STATES.STATE_NAME || ', ') || COUNTRY.CY_CODE EVENT_DESCRIPTION,   
		RQBK_OC_CARRIER.RQOC_SAIL_DATE-2 EXPECTED_DATE_1,   
		DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_FCL_HDR.RQFH_ARR_PORT_EXPORT, RQBK_LCL_HDR.RQLH_ARR_PORT_EXPORT) ACTUAL_DATE,   
		RQBK_IDX.RQI_RQBK_ID BOOKING_ID,   
		RQBK_OC_CARRIER.RQOC_SAIL_DATE - 2 EXPECTED_DATE_2
	FROM 
    RQBK_FCL_HDR,   
		RQBK_LCL_HDR,   
		RQBK_IDX,   
		RQBK_OC_CARRIER,   
		RQBK_MC,   
		CITY,   
		STATES,   
		COUNTRY,   
		VESSELS   
	WHERE RQBK_IDX.RQI_RQBK_ID = RQBK_FCL_HDR.RQFH_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_OC_CARRIER.RQOC_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_MC.RQM_RQBK_ID   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_LCL_HDR.RQLH_RQBK_ID (+)   
		AND RQBK_MC.RQM_PORT_EXPORT = CITY.CT_ID   
		AND CITY.CT_STATE_ID = STATES.STATE_ID (+)   
		AND CITY.CT_COUNTRY_ID = COUNTRY.CY_ID   
		AND RQBK_OC_CARRIER.RQOC_VS_NAME = VESSELS.VS_ID
		AND RQBK_IDX.RQI_RQBK_ID = V_BOOKING_ID 

	UNION

	SELECT 
    DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_FCL_HDR.RQFH_CONT_NUM, 'LCL') CONTAINER_NUMBER,   
		VESSELS.VS_NAME VESSEL_NAME,   
		RQBK_OC_CARRIER.RQOC_VOYAGE VOYAGE_NUMBER,   
		'Arrived at Port of Discharge: ' || CITY.CT_DESC || ', ' || DECODE(STATES.STATE_NAME, NULL, '', STATES.STATE_NAME || ', ') || COUNTRY.CY_CODE EVENT_DESCRIPTION,   
		RQBK_OC_CARRIER.RQOC_PORT_DISCHARGE_ARR_DATE EXPECTED_DATE_1,   
		RQBK_OC_CARRIER.RQOC_ACT_PORT_DISCHARGE_DATE ACTUAL_DATE,   
		RQBK_IDX.RQI_RQBK_ID BOOKING_ID,   
		RQBK_OC_CARRIER.RQOC_PORT_DISCHARGE_ARR_DATE EXPECTED_DATE_2	  
	FROM 
    RQBK_FCL_HDR,   
		RQBK_IDX,   
		RQBK_OC_CARRIER,   
		RQBK_MC,   
		CITY,   
		STATES,   
		COUNTRY,   
		VESSELS   
	WHERE RQBK_IDX.RQI_RQBK_ID = RQBK_FCL_HDR.RQFH_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_OC_CARRIER.RQOC_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_MC.RQM_RQBK_ID   
		AND RQBK_MC.RQM_PORT_DISCHARGE = CITY.CT_ID   
		AND CITY.CT_STATE_ID = STATES.STATE_ID (+)   
		AND CITY.CT_COUNTRY_ID = COUNTRY.CY_ID   
		AND RQBK_OC_CARRIER.RQOC_VS_NAME = VESSELS.VS_ID        
		AND RQBK_IDX.RQI_RQBK_ID = V_BOOKING_ID

	UNION

	SELECT 
    DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_FCL_HDR.RQFH_CONT_NUM,'LCL') CONTAINER_NUMBER,   
		VESSELS.VS_NAME VESSEL_NAME,   
		RQBK_OC_CARRIER.RQOC_VOYAGE VOYAGE_NUMBER,   
		'Arrived at Place of Delivery: ' || CITY.CT_DESC || ', ' || DECODE(STATES.STATE_NAME, NULL, '', STATES.STATE_NAME || ', ') || COUNTRY.CY_CODE EVENT_DESCRIPTION,   
		RQBK_OC_CARRIER.RQOC_POD_ARR_DATE EXPECTED_DATE_1,   
		RQBK_OC_CARRIER.RQOC_ACT_POD_ARR_DATE ACTUAL_DATE,   
		RQBK_IDX.RQI_RQBK_ID BOOKING_ID,   
		RQBK_OC_CARRIER.RQOC_POD_ARR_DATE EXPECTED_DATE_2  
	FROM 
    RQBK_FCL_HDR,   
		RQBK_IDX,   
		RQBK_OC_CARRIER,   
		RQBK_MC,   
		CITY,   
		STATES,   
		COUNTRY,   
		VESSELS   
	WHERE RQBK_IDX.RQI_RQBK_ID = RQBK_FCL_HDR.RQFH_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_OC_CARRIER.RQOC_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_MC.RQM_RQBK_ID   
		AND RQBK_MC.RQM_POD = CITY.CT_ID   
		AND CITY.CT_STATE_ID = STATES.STATE_ID (+)   
		AND CITY.CT_COUNTRY_ID = COUNTRY.CY_ID   
		AND RQBK_OC_CARRIER.RQOC_VS_NAME = VESSELS.VS_ID   
		AND RQBK_OC_CARRIER.RQOC_POD_ARR_DATE <> RQBK_OC_CARRIER.RQOC_PORT_DISCHARGE_ARR_DATE   
		AND RQBK_IDX.RQI_RQBK_ID = V_BOOKING_ID

	UNION

	SELECT 
    DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_FCL_HDR.RQFH_CONT_NUM, 'LCL') CONTAINER_NUMBER,   
		VESSELS.VS_NAME VESSEL_NAME,   
		RQBK_OC_CARRIER.RQOC_VOYAGE VOYAGE_NUMBER,   
		'Arrived CY/CFS: ' || CITY.CT_DESC || ', ' || DECODE(STATES.STATE_NAME, NULL, '', STATES.STATE_NAME || ', ') || COUNTRY.CY_CODE EVENT_DESCRIPTION,   
		RQBK_OC_CARRIER.RQOC_PC_TERM_CUTOFF EXPECTED_DATE_1,   
		DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_FCL_HDR.RQFH_ARR_TERM, RQBK_LCL_HDR.RQLH_ARR_TERM) ACTUAL_DATE,   
		RQBK_IDX.RQI_RQBK_ID BOOKING_ID,   
		RQBK_OC_CARRIER.RQOC_PC_TERM_CUTOFF EXPECTED_DATE_2          
	FROM 
    RQBK_FCL_HDR,   
		RQBK_LCL_HDR,   
		RQBK_IDX,   
		RQBK_OC_CARRIER,   
		RQBK_MC,   
		RQ_PRE_CARRIAGE,   
		CITY,   
		STATES,   
		COUNTRY,   
		VESSELS   
	WHERE RQBK_IDX.RQI_RQBK_ID = RQBK_FCL_HDR.RQFH_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_LCL_HDR.RQLH_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_OC_CARRIER.RQOC_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQ_PRE_CARRIAGE.RQPC_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_MC.RQM_RQBK_ID   
		AND RQ_PRE_CARRIAGE.RQPC_POR = CITY.CT_ID   
		AND CITY.CT_STATE_ID = STATES.STATE_ID (+)   
		AND CITY.CT_COUNTRY_ID = COUNTRY.CY_ID   
		AND RQBK_OC_CARRIER.RQOC_VS_NAME = VESSELS.VS_ID   
		AND RQBK_IDX.RQI_RQBK_ID = V_BOOKING_ID 
		AND RQ_PRE_CARRIAGE.RQPC_NUMBER = 2  -- Indicates intermodal

	UNION

	SELECT 
    DECODE(RQBK_IDX.RQI_FCL_LCL, 1, RQBK_FCL_HDR.RQFH_CONT_NUM, 'LCL') CONTAINER_NUMBER,   
		VESSELS.VS_NAME VESSEL_NAME,   
		RQBK_OC_CARRIER.RQOC_VOYAGE VOYAGE_NUMBER,   
		'Departed CY/CFS: ' || CITY.CT_DESC || ', ' || DECODE(STATES.STATE_NAME, NULL, '', STATES.STATE_NAME || ', ') || COUNTRY.CY_CODE EVENT_DESCRIPTION,   
		RQBK_OC_CARRIER.RQOC_PC_TERM_CUTOFF+1 EXPECTED_DATE_1,   
		DECODE(RQBK_IDX.RQI_FCL_LCL,1,RQBK_FCL_HDR.RQFH_DPT_TERM,RQBK_LCL_HDR.RQLH_DPT_TERM) ACTUAL_DATE,   
		RQBK_IDX.RQI_RQBK_ID BOOKING_ID,   
		RQBK_OC_CARRIER.RQOC_PC_TERM_CUTOFF+1 EXPECTED_DATE_2   
	FROM 
    RQBK_FCL_HDR,   
		RQBK_LCL_HDR,   
		RQBK_IDX,   
		RQBK_OC_CARRIER,   
		RQBK_MC,   
		RQ_PRE_CARRIAGE,   
		CITY,   
		STATES,   
		COUNTRY,   
		VESSELS
	WHERE RQBK_IDX.RQI_RQBK_ID = RQBK_FCL_HDR.RQFH_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_LCL_HDR.RQLH_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_OC_CARRIER.RQOC_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQ_PRE_CARRIAGE.RQPC_RQBK_ID (+)   
		AND RQBK_IDX.RQI_RQBK_ID = RQBK_MC.RQM_RQBK_ID   
		AND RQ_PRE_CARRIAGE.RQPC_POR = CITY.CT_ID   
		AND CITY.CT_STATE_ID = STATES.STATE_ID (+)   
		AND CITY.CT_COUNTRY_ID = COUNTRY.CY_ID   
		AND RQBK_OC_CARRIER.RQOC_VS_NAME = VESSELS.VS_ID   
		AND RQBK_IDX.RQI_RQBK_ID = V_BOOKING_ID   
		AND RQ_PRE_CARRIAGE.RQPC_NUMBER = 2  -- Indicates intermodal, Intermodal pre-carrier = 2   
		ORDER BY EXPECTED_DATE_2;

	EXCEPTION WHEN OTHERS THEN    
		RAISE;
END;