create or replace PROCEDURE SP_PORTAL_DETAIL_REFERENCE
(
  I_HARBOUR_NUMBER IN VARCHAR2, 
  I_REFERENCE_TYPE IN VARCHAR2,
  O_CURSOR OUT SYS_REFCURSOR
)
AS 
BEGIN
	OPEN O_CURSOR FOR
	SELECT 
    RQR_RQBK_ID BOOKING_ID, 
		RQR_REF_TYPE REFERENCE_TYPE, 
		RQR_REF_NUM REFERENCE_NUNBER 
	FROM 
    RQBK_IDX, 
    RQBK_REF 
	WHERE RQI_RQBK_NUM = I_HARBOUR_NUMBER
		AND RQI_RQBK_ID = RQR_RQBK_ID
		AND RQR_REF_TYPE = TO_NUMBER(I_REFERENCE_TYPE)
  ORDER BY REFERENCE_NUNBER DESC;   
	EXCEPTION WHEN OTHERS THEN                       
		RAISE;
END;