create or replace PROCEDURE SP_PORTAL_DETAIL_LCL_TOTAL
(
  I_HARBOUR_NUMBER IN VARCHAR2,  
  O_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
  OPEN O_CURSOR FOR
  SELECT 
    RQLH_CONT_ID CONTAINER_ID,	
    RQLH_TOT_PIECES TOTAL_PIECES, 
    RQLH_TOT_LBS TOTAL_WEIGHT,
    RQLH_TOT_CUFT TOTAL_VOLUME
  FROM
    RQBK_IDX, 
    RQBK_LCL_HDR
  WHERE RQI_RQBK_NUM = I_HARBOUR_NUMBER
    AND RQI_RQBK_ID = RQLH_RQBK_ID;    
  EXCEPTION WHEN OTHERS THEN                       
    RAISE; 
END;