create or replace PROCEDURE SP_PORTAL_SEARCH_TERMS
(
	i_COMPANY_ID IN VARCHAR2,
	i_COMPANY_TYPE IN VARCHAR2,
	i_SEARCH_TYPE IN VARCHAR2,
	o_CURSOR OUT SYS_REFCURSOR
)
AS

	v_COMPANY_ID CONSTANT NUMBER := TO_NUMBER(i_COMPANY_ID);   -- cast is required due to .NET EF bug

BEGIN

  IF (i_COMPANY_TYPE != 1 AND i_COMPANY_TYPE != 2) THEN  -- not a Shipper or Consignee company
    RETURN;
  END IF;

  IF (i_SEARCH_TYPE = 'HN') THEN  -- HarbourNumber
    OPEN o_CURSOR FOR
    SELECT DISTINCT
      RQBK_IDX.RQI_RQBK_NUM SEARCH_TERM_KEY,    -- Key: Harbour Number  (Booking / Rate Quote)
      RQBK_IDX.RQI_RQBK_NUM SEARCH_TERM_VALUE   -- Value: Harbour Number
    FROM
      RQBK_IDX,
      RQBK_SH_CS
    WHERE RQBK_IDX.RQI_COMPLETE = -1   -- Completed Transaction
      AND RQBK_IDX.RQI_ACTIVE = -1     -- Active Transaction
      AND RQBK_IDX.RQI_RQBK = 2        -- Booking Type
      AND RQBK_IDX.RQI_RQBK_ID = RQBK_SH_CS.RQSC_RQBK_ID
      AND DECODE(i_COMPANY_TYPE, 1, RQBK_SH_CS.RQSC_SH_ID, 2, RQBK_SH_CS.RQSC_CS_ID) = v_COMPANY_ID   -- Decode: Shipper = 1, Consignee = 2
    ORDER BY RQBK_IDX.RQI_RQBK_NUM ASC;
  END IF;

  IF (i_SEARCH_TYPE = 'CBN') THEN  -- CarrierBookingNumber
    OPEN o_CURSOR FOR
    SELECT DISTINCT
      RQBK_OC_CARRIER.RQOC_BK_NUM SEARCH_TERM_KEY,   -- Key: Carrier Booking Number
      RQBK_IDX.RQI_RQBK_NUM SEARCH_TERM_VALUE        -- Value: Harbour Number
    FROM
      RQBK_IDX,
      RQBK_SH_CS,
      RQBK_OC_CARRIER
    WHERE RQBK_IDX.RQI_COMPLETE = -1
      AND RQBK_IDX.RQI_ACTIVE = -1
      AND RQBK_IDX.RQI_RQBK = 2
      AND RQBK_IDX.RQI_RQBK_ID = RQBK_SH_CS.RQSC_RQBK_ID
      AND DECODE(i_COMPANY_TYPE, 1, RQBK_SH_CS.RQSC_SH_ID, 2, RQBK_SH_CS.RQSC_CS_ID) = v_COMPANY_ID
      AND RQBK_IDX.RQI_RQBK_ID = RQBK_OC_CARRIER.RQOC_RQBK_ID (+)
      AND RQBK_OC_CARRIER.RQOC_BK_NUM IS NOT NULL
    ORDER BY RQBK_OC_CARRIER.RQOC_BK_NUM ASC;
  END IF;

  IF (i_SEARCH_TYPE = 'SR') THEN  -- ShipperReferenceNumber
    OPEN o_CURSOR FOR 
    SELECT DISTINCT
      RQBK_REF.RQR_REF_NUM SEARCH_TERM_KEY,     -- Key: Shipper Reference Number
      RQBK_IDX.RQI_RQBK_NUM SEARCH_TERM_VALUE   -- Value: Harbour Number
    FROM
      RQBK_IDX,
      RQBK_SH_CS,
      RQBK_REF
    WHERE RQBK_IDX.RQI_COMPLETE = -1
      AND RQBK_IDX.RQI_ACTIVE = -1
      AND RQBK_IDX.RQI_RQBK = 2
      AND RQBK_IDX.RQI_RQBK_ID = RQBK_SH_CS.RQSC_RQBK_ID
      AND DECODE(i_COMPANY_TYPE, 1, RQBK_SH_CS.RQSC_SH_ID, 2, RQBK_SH_CS.RQSC_CS_ID) = v_COMPANY_ID
      AND RQBK_IDX.RQI_RQBK_ID = RQBK_REF.RQR_RQBK_ID (+)
      AND RQBK_REF.RQR_REF_TYPE = 1   -- Shipper Reference
      AND RQBK_REF.RQR_REF_NUM IS NOT NULL
    ORDER BY RQBK_REF.RQR_REF_NUM ASC;
  END IF;

  IF (i_SEARCH_TYPE = 'CR') THEN  -- ConsigneeReferenceNumber
    OPEN o_CURSOR FOR 
    SELECT DISTINCT
      RQBK_REF.RQR_REF_NUM SEARCH_TERM_KEY,     -- Key: Consignee Reference Number
      RQBK_IDX.RQI_RQBK_NUM SEARCH_TERM_VALUE   -- Value: Harbour Number
    FROM
      RQBK_IDX,
      RQBK_SH_CS,
      RQBK_REF 
    WHERE RQBK_IDX.RQI_COMPLETE = -1
      AND RQBK_IDX.RQI_ACTIVE = -1
      AND RQBK_IDX.RQI_RQBK = 2
      AND RQBK_IDX.RQI_RQBK_ID = RQBK_SH_CS.RQSC_RQBK_ID
      AND DECODE(i_COMPANY_TYPE, 1, RQBK_SH_CS.RQSC_SH_ID, 2, RQBK_SH_CS.RQSC_CS_ID) = v_COMPANY_ID
      AND RQBK_IDX.RQI_RQBK_ID = RQBK_REF.RQR_RQBK_ID (+)
      AND RQBK_REF.RQR_REF_TYPE = 2   -- Consignee Reference
      AND RQBK_REF.RQR_REF_NUM IS NOT NULL
    ORDER BY RQBK_REF.RQR_REF_NUM ASC;
  END IF;

  IF (i_SEARCH_TYPE = 'AWN') THEN  -- AirWaybillNumber
    OPEN o_CURSOR FOR
    SELECT DISTINCT
      RQBK_AIR_CARRIER.RQAC_AWB_NUM SEARCH_TERM_KEY,   -- Key: Air Waybill Number
      RQBK_IDX.RQI_RQBK_NUM SEARCH_TERM_VALUE          -- Value: Harbour Number
    FROM
      RQBK_IDX,
      RQBK_SH_CS,
      RQBK_AIR_CARRIER 
    WHERE RQBK_IDX.RQI_COMPLETE = -1
      AND RQBK_IDX.RQI_ACTIVE = -1
      AND RQBK_IDX.RQI_RQBK = 2
      AND RQBK_IDX.RQI_RQBK_ID = RQBK_SH_CS.RQSC_RQBK_ID
      AND DECODE(i_COMPANY_TYPE, 1, RQBK_SH_CS.RQSC_SH_ID, 2, RQBK_SH_CS.RQSC_CS_ID) = v_COMPANY_ID
      AND RQBK_IDX.RQI_RQBK_ID = RQBK_AIR_CARRIER.RQAC_RQBK_ID (+)
      AND RQBK_AIR_CARRIER.RQAC_AWB_NUM IS NOT NULL
    ORDER BY RQBK_AIR_CARRIER.RQAC_AWB_NUM ASC;
  END IF;

  IF (i_SEARCH_TYPE = 'NBN') THEN  -- NVOBookingNumber
    OPEN o_CURSOR FOR 
    SELECT DISTINCT
      RQBK_OC_CARRIER.RQOC_NVO_NUM SEARCH_TERM_KEY,   -- Key: NVO Booking Number
      RQBK_IDX.RQI_RQBK_NUM SEARCH_TERM_VALUE         -- Value: Harbour Number
    FROM
      RQBK_IDX, 
      RQBK_SH_CS,
      RQBK_OC_CARRIER 
    WHERE RQBK_IDX.RQI_COMPLETE = -1
      AND RQBK_IDX.RQI_ACTIVE = -1
      AND RQBK_IDX.RQI_RQBK = 2
      AND RQBK_IDX.RQI_RQBK_ID = RQBK_SH_CS.RQSC_RQBK_ID
      AND DECODE(i_COMPANY_TYPE, 1, RQBK_SH_CS.RQSC_SH_ID, 2, RQBK_SH_CS.RQSC_CS_ID) = v_COMPANY_ID
      AND RQBK_IDX.RQI_RQBK_ID = RQBK_OC_CARRIER.RQOC_RQBK_ID (+)
      AND RQBK_OC_CARRIER.RQOC_NVO_NUM IS NOT NULL
    ORDER BY RQBK_OC_CARRIER.RQOC_NVO_NUM ASC;
  END IF;

  IF (i_SEARCH_TYPE = 'POD-O') THEN  -- PlaceOfDeleivery [Ocean]
    OPEN o_CURSOR FOR 
    SELECT DISTINCT
      CITY.CT_DESC SEARCH_TERM_KEY,           -- Key: Place of Deleivery
      TO_CHAR(CITY.CT_ID) SEARCH_TERM_VALUE   -- Value: CITY ID
    FROM
      RQBK_IDX,
      RQBK_SH_CS,
      CITY
    WHERE RQBK_IDX.RQI_COMPLETE = -1
      AND RQBK_IDX.RQI_ACTIVE = -1
      AND RQBK_IDX.RQI_RQBK = 2
      AND RQBK_IDX.RQI_RQBK_ID = RQBK_SH_CS.RQSC_RQBK_ID
      AND DECODE(i_COMPANY_TYPE, 1, RQBK_SH_CS.RQSC_SH_ID, 2, RQBK_SH_CS.RQSC_CS_ID) = v_COMPANY_ID
      AND RQBK_SH_CS.RQSC_POD = CITY.CT_ID   -- Ocean
      --AND (RQBK_SH_CS.RQSC_POD_AIR = CITY_AIR.CT_ID OR RQBK_SH_CS.RQSC_POD = CITY_OCEAN.CT_ID)   -- Ocean and Air ??
      AND CITY.CT_DESC IS NOT NULL
    ORDER BY CITY.CT_DESC ASC;
  END IF;

  IF (i_SEARCH_TYPE = 'POD-A') THEN  -- PlaceOfDeleivery [Air]
    OPEN o_CURSOR FOR 
    SELECT DISTINCT
      AIRPORTS.AP_CODE SEARCH_TERM_KEY,    -- Key: Place of Deleivery (Airport Code)
      AIRPORTS.AP_CODE SEARCH_TERM_VALUE   -- Value: Place of Deleivery (Airport Code)
    FROM
      RQBK_IDX,
      RQBK_SH_CS,
      AIRPORTS      
    WHERE RQBK_IDX.RQI_COMPLETE = -1
      AND RQBK_IDX.RQI_ACTIVE = -1
      AND RQBK_IDX.RQI_RQBK = 2
      AND RQBK_IDX.RQI_RQBK_ID = RQBK_SH_CS.RQSC_RQBK_ID
      AND DECODE(i_COMPANY_TYPE, 1, RQBK_SH_CS.RQSC_SH_ID, 2, RQBK_SH_CS.RQSC_CS_ID) = v_COMPANY_ID
      AND RQBK_SH_CS.RQSC_POD_AIR =  AIRPORTS.AP_ID (+)   -- Air      
      AND AIRPORTS.AP_CODE IS NOT NULL
    ORDER BY AIRPORTS.AP_CODE ASC;
  END IF;

  IF (i_SEARCH_TYPE = 'SN' OR i_SEARCH_TYPE = 'CN') THEN  -- Shipper Name or Consignee Name
    OPEN o_CURSOR FOR
    SELECT DISTINCT
      INITCAP(COMPANY.CO_NAME) SEARCH_TERM_KEY,   -- Key: Shipper/Consignee Name
      TO_CHAR(COMPANY.CO_ID) SEARCH_TERM_VALUE    -- Value: Company ID
    FROM
      RQBK_IDX,
      RQBK_SH_CS,
      COMPANY
    WHERE RQBK_IDX.RQI_COMPLETE = -1
      AND RQBK_IDX.RQI_ACTIVE = -1
      AND RQBK_IDX.RQI_RQBK = 2
      AND RQBK_IDX.RQI_RQBK_ID = RQBK_SH_CS.RQSC_RQBK_ID
      AND DECODE(i_COMPANY_TYPE, 1, RQBK_SH_CS.RQSC_SH_ID, 2, RQBK_SH_CS.RQSC_CS_ID) = v_COMPANY_ID
      AND DECODE(i_COMPANY_TYPE, 2, RQBK_SH_CS.RQSC_SH_ID, 1, RQBK_SH_CS.RQSC_CS_ID) = COMPANY.CO_ID
      AND COMPANY.CO_NAME IS NOT NULL
    ORDER BY SEARCH_TERM_KEY ASC;
  END IF;
  
	EXCEPTION WHEN OTHERS THEN
		RAISE;
END;