create or replace PROCEDURE SP_PORTAL_EVENTS_AIR
(
	I_HARBOUR_NUMBER IN VARCHAR2,
	O_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
	OPEN O_CURSOR FOR
  
	SELECT
		AIR1.AP_CODE DEPARTURE_AIRPORT_CODE,
		RQAF_AR_FLIGHTS.RQAF_FLIGHT_NUM FLIGHT_NUMBER,
		RQAF_AR_FLIGHTS.RQAF_ACT_DPT_DATE FLIGHT_DATE,
		AIR2.AP_CODE ARRIVAL_AIRPORT_CODE,
		'Arrived at Warehouse' EVENT_DESCRIPTION,
		RQBK_AIR_CARRIER.RQAC_IN_WHSE_CUTOFF EXPECTED_DATE,
		RQBK_AIR_CARRIER.RQAC_ARR_WHSE ACTUAL_DATE,
		RQBK_IDX.RQI_RQBK_ID BOOKING_ID
	FROM
		RQBK_IDX,
		RQBK_AIR_CARRIER,
		RQAF_AR_FLIGHTS,
		AIRPORTS AIR1,
		AIRPORTS AIR2
	WHERE RQBK_IDX.RQI_RQBK_ID = RQBK_AIR_CARRIER.RQAC_RQBK_ID (+)
		AND RQBK_IDX.RQI_RQBK_ID = RQAF_AR_FLIGHTS.RQAF_RQBK_ID (+)
		AND RQAF_AR_FLIGHTS.RQAF_DPT_AIRPORT = AIR1.AP_ID
		AND RQAF_AR_FLIGHTS.RQAF_ARR_AIRPORT = AIR2.AP_ID
		AND RQBK_IDX.RQI_RQBK = 2       /*Booking*/
		AND RQBK_IDX.RQI_COMPLETE = -1  /*Completed*/
		AND RQBK_IDX.RQI_ACTIVE = -1
		AND RQBK_IDX.RQI_RQBK_TYPE = 2  /*Air*/
		AND RQAF_AR_FLIGHTS.RQAF_FLIGHT_LEG = 1
		AND RQBK_IDX.RQI_RQBK_NUM = I_HARBOUR_NUMBER

	UNION

	SELECT
		AIR1.AP_CODE DEPARTURE_AIRPORT_CODE,
		RQAF_AR_FLIGHTS.RQAF_FLIGHT_NUM FLIGHT_NUMBER,
		RQAF_AR_FLIGHTS.RQAF_ACT_DPT_DATE FLIGHT_DATE,
		AIR2.AP_CODE ARRIVAL_AIRPORT_CODE,
		'Arrived at Airport' EVENT_DESCRIPTION,
		RQBK_AIR_CARRIER.RQAC_LOCKOUT EXPECTED_DATE,
		RQBK_AIR_CARRIER.RQAC_ARR_AIRPORT ACTUAL_DATE,
		RQBK_IDX.RQI_RQBK_ID BOOKING_ID
	FROM RQBK_IDX,
		RQBK_AIR_CARRIER,
		RQAF_AR_FLIGHTS,
		AIRPORTS AIR1,
		AIRPORTS AIR2
	WHERE RQBK_IDX.RQI_RQBK_ID = RQBK_AIR_CARRIER.RQAC_RQBK_ID (+)
		AND RQBK_IDX.RQI_RQBK_ID = RQAF_AR_FLIGHTS.RQAF_RQBK_ID (+)
		AND RQAF_AR_FLIGHTS.RQAF_DPT_AIRPORT = AIR1.AP_ID
		AND RQAF_AR_FLIGHTS.RQAF_ARR_AIRPORT = AIR2.AP_ID
		AND RQBK_IDX.RQI_RQBK = 2       /*Booking*/
		AND RQBK_IDX.RQI_COMPLETE = -1  /*Ccompleted*/
		AND RQBK_IDX.RQI_ACTIVE = -1
		AND RQBK_IDX.RQI_RQBK_TYPE = 2  /*Air*/
		AND RQAF_AR_FLIGHTS.RQAF_FLIGHT_LEG = 1
		AND RQBK_IDX.RQI_RQBK_NUM = I_HARBOUR_NUMBER

	UNION

	SELECT
		AIR1.AP_CODE DEPARTURE_AIRPORT_CODE,
		RQAF_AR_FLIGHTS.RQAF_FLIGHT_NUM FLIGHT_NUMBER,
		RQAF_AR_FLIGHTS.RQAF_ACT_DPT_DATE FLIGHT_DATE,
		AIR2.AP_CODE ARRIVAL_AIRPORT_CODE,
		'Flight Departed' EVENT_DESCRIPTION,
		RQAF_AR_FLIGHTS.RQAF_SCHED_DPT_DATE EXPECTED_DATE,
		--RQAF_AR_FLIGHTS.RQAF_ACT_DPT_DATE ACTUAL_DATE,
		Null, --FJM 02/08/2004 - Removed due to bug in actual depature date being set premature.  Remove from tracing till bug is fixed.
		RQBK_IDX.RQI_RQBK_ID BOOKING_ID
	FROM RQBK_IDX,
		RQBK_AIR_CARRIER,
		RQAF_AR_FLIGHTS,
		AIRPORTS AIR1,
		AIRPORTS AIR2
	WHERE RQBK_IDX.RQI_RQBK_ID = RQBK_AIR_CARRIER.RQAC_RQBK_ID (+)
		AND RQBK_IDX.RQI_RQBK_ID = RQAF_AR_FLIGHTS.RQAF_RQBK_ID (+)
		AND RQAF_AR_FLIGHTS.RQAF_DPT_AIRPORT = AIR1.AP_ID
		AND RQAF_AR_FLIGHTS.RQAF_ARR_AIRPORT = AIR2.AP_ID
		AND RQBK_IDX.RQI_RQBK = 2       /*Booking*/
		AND RQBK_IDX.RQI_COMPLETE = -1  /*Ccompleted*/
		AND RQBK_IDX.RQI_ACTIVE = -1
		AND RQBK_IDX.RQI_RQBK_TYPE = 2  /*Air*/
		AND RQBK_IDX.RQI_RQBK_NUM = I_HARBOUR_NUMBER;

	EXCEPTION WHEN OTHERS THEN
		RAISE;
END;