create or replace PROCEDURE SP_PORTAL_GRID_LOAD
(
	i_USER_ID IN VARCHAR2,
  i_SEARCH_TYPE IN VARCHAR2,
  i_SEARCH_TERM  IN VARCHAR2,
	o_CURSOR OUT SYS_REFCURSOR
)
AS

  v_USER_ID CONSTANT NUMBER := TO_NUMBER(i_USER_ID);   -- cast required due to .NET EF bug
	v_COMPANY_ID NUMBER;
	v_COMPANY_TYPE NUMBER;

BEGIN

	SELECT COMPANY.CO_ID, COMPANY.CO_TYPE
	INTO v_COMPANY_ID, v_COMPANY_TYPE
	FROM COMPANY, CONTACTS
	WHERE CONTACTS.CONT_CO_ID = COMPANY.CO_ID
		AND CONTACTS.CONT_ID = v_USER_ID;  

	IF (v_COMPANY_TYPE != 1 AND v_COMPANY_TYPE != 2) THEN  -- not a Shipper or Consignee company
    RETURN;  
  END IF;

  OPEN o_CURSOR FOR
  SELECT DISTINCT
    RQI_RQBK_NUM HARBOUR_NUMBER,
    TRUNC(RQI_DATE_REQUESTED) REQUEST_DATE,
    initcap(DECODE(v_COMPANY_TYPE, 1, DECODE(RQSC_CS_ID, NULL, RQSC_CS_NAME, CONSIGNEE.CO_NAME), 2, DECODE(RQSC_SH_ID, NULL, RQSC_SH_NAME, SHIPPER.CO_NAME))) COMPANY_NAME,
    DECODE(RQSC_POD_NAME, NULL, DECODE(RQSC_POD, NULL, PODAIR.AP_CODE, PODCITY.CT_DESC || DECODE(PODSTATES.STATE_CODE, NULL, ', ', ', ' || PODSTATES.STATE_CODE || ', ') || PODCOUNTRY.CY_CODE), RQSC_POD_NAME) PLACE_OF_DELIVERY,
    DECODE(RQSC_POR_NAME, NULL, DECODE(RQSC_POR, NULL, PORAIR.AP_CODE, PORCITY.CT_DESC || DECODE(PORSTATES.STATE_CODE, NULL, ', ', ', ' || PORSTATES.STATE_CODE || ', ') || PORCOUNTRY.CY_CODE), RQSC_POR_NAME) PLACE_OF_RECEIPT,
    DECODE(RQI_FCL_LCL, NULL, 'Air', 1, FUNCTION_PORTAL_FCL_TYPES(RQI_RQBK_ID, 2), RQCT_DESC) FILL_TYPE,
    initcap(RQM_COMM_NAME) COMMODITY,
    HPT_HAZARDOUS HAZARD_FLAG
  FROM
    RQBK_IDX,
    RQBK_SH_CS,    
    COMPANY SHIPPER,
    COMPANY CONSIGNEE,
    CITY PODCITY,
    RQBK_CONTAINER_TYPE,
    RQBK_MC,
    HAZARD_PERISH_TYPES,
    STATES PODSTATES,
    COUNTRY PODCOUNTRY,
    CITY PORCITY,
    STATES PORSTATES,
    COUNTRY PORCOUNTRY,
    AIRPORTS PODAIR,
    AIRPORTS PORAIR    
	WHERE RQBK_IDX.RQI_COMPLETE = -1   -- Completed Transaction
    AND RQBK_IDX.RQI_ACTIVE = -1     -- Active Transaction
    AND RQBK_IDX.RQI_RQBK = 2        -- Booking Type (RateQuote=1, Booking=2)
    AND RQBK_IDX.RQI_RQBK_ID = RQBK_SH_CS.RQSC_RQBK_ID (+)
    AND RQBK_IDX.RQI_RQBK_ID = RQBK_MC.RQM_RQBK_ID (+)
    AND RQBK_IDX.RQI_FCL_LCL = RQBK_CONTAINER_TYPE.RQCT_ID (+)
    AND RQBK_MC.RQM_HAZ_PERISH = HAZARD_PERISH_TYPES.HPT_ID (+)
    
    AND RQBK_SH_CS.RQSC_POD = PODCITY.CT_ID (+)
    AND PODCITY.CT_STATE_ID = PODSTATES.STATE_ID (+) 
    AND PODCITY.CT_COUNTRY_ID = PODCOUNTRY.CY_ID (+)
    AND RQBK_SH_CS.RQSC_POD_AIR = PODAIR.AP_ID (+)
    
    AND RQBK_SH_CS.RQSC_POR = PORCITY.CT_ID (+)
    AND PORCITY.CT_STATE_ID = PORSTATES.STATE_ID (+)
    AND PORCITY.CT_COUNTRY_ID = PORCOUNTRY.CY_ID (+)
    AND RQBK_SH_CS.RQSC_POR_AIR = PORAIR.AP_ID (+)
    
    AND RQBK_SH_CS.RQSC_SH_ID = SHIPPER.CO_ID (+) 
    AND RQBK_SH_CS.RQSC_CS_ID = CONSIGNEE.CO_ID (+)
    AND DECODE(v_COMPANY_TYPE, 1, RQBK_SH_CS.RQSC_SH_ID, 2, RQBK_SH_CS.RQSC_CS_ID) = v_COMPANY_ID   -- Decode: Shipper = 1, Consignee = 2
    
    AND 
    (
      (i_SEARCH_TYPE = 'CI') OR   -- Company ID
      (i_SEARCH_TYPE = 'HN' AND RQI_RQBK_NUM = i_SEARCH_TERM) OR   -- Harbour number
      (i_SEARCH_TYPE = 'CN' AND DECODE(v_COMPANY_TYPE, 2, RQBK_SH_CS.RQSC_SH_ID, 1, RQBK_SH_CS.RQSC_CS_ID) = i_SEARCH_TERM)   -- Company name
      
      
      
      
    )
    
    
    
--    CASE i_SEARCH_TYPE
--      WHEN 'HN' THEN 'The owner is SYS'
--      WHEN 'CBN' THEN 'The owner is SYSTEM'
--    END
        
  ORDER BY REQUEST_DATE DESC;

	EXCEPTION WHEN OTHERS THEN
		RAISE;
END;