create or replace PROCEDURE SP_PORTAL_GRID
(
	I_USERID IN VARCHAR2,
	O_CURSOR OUT SYS_REFCURSOR
)
AS

	UserID CONSTANT NUMBER := TO_NUMBER(I_USERID);   -- Varchar2 to Number cast is required due to .NET EF bug
	CompanyID NUMBER;
	CompanyType NUMBER;

BEGIN
	SELECT COMPANY.CO_ID, COMPANY.CO_TYPE
	INTO CompanyID, CompanyType
	FROM COMPANY, CONTACTS
	WHERE CONT_ID = UserID
		AND CONT_CO_ID = CO_ID;

	IF (CompanyType = 1 OR CompanyType = 2) THEN -- Shipper or Consignee Company
		OPEN O_CURSOR FOR
		SELECT DISTINCT
			RQI_RQBK_NUM HARBOUR_NUMBER,
			TRUNC(RQI_DATE_REQUESTED) REQUEST_DATE,
			initcap(DECODE(CompanyType, 1, DECODE(RQSC_CS_ID, NULL, RQSC_CS_NAME, CONSIGNEE.CO_NAME), 2, DECODE(RQSC_SH_ID, NULL, RQSC_SH_NAME, SHIPPER.CO_NAME))) COMPANY_NAME,
			DECODE(RQSC_POD_NAME, NULL, DECODE(RQSC_POD, NULL, PODAIR.AP_CODE, PODCITY.CT_DESC || DECODE(PODSTATES.STATE_CODE, NULL, ', ', ', ' || PODSTATES.STATE_CODE || ', ') || PODCOUNTRY.CY_CODE), RQSC_POD_NAME) PLACE_OF_DELIVERY,
			DECODE(RQSC_POR_NAME, NULL, DECODE(RQSC_POR, NULL, PORAIR.AP_CODE, PORCITY.CT_DESC || DECODE(PORSTATES.STATE_CODE, NULL, ', ', ', ' || PORSTATES.STATE_CODE || ', ') || PORCOUNTRY.CY_CODE), RQSC_POR_NAME) PLACE_OF_RECEIPT,
			DECODE(RQI_FCL_LCL, NULL, 'Air', 1, FUNCTION_PORTAL_FCL_TYPES(RQI_RQBK_ID, 2), RQCT_DESC) FILL_TYPE,
			initcap(RQM_COMM_NAME) COMMODITY,
			HPT_HAZARDOUS HAZARD_FLAG
		FROM
			RQBK_IDX,
			RQBK_SH_CS,
			RQBK_AIR_CARRIER,
			RQBK_OC_CARRIER,
			COMPANY SHIPPER,
			COMPANY CONSIGNEE,
			CITY PODCITY,
			RQBK_CONTAINER_TYPE,
			RQBK_MC,
			HAZARD_PERISH_TYPES,
			STATES PODSTATES,
			COUNTRY PODCOUNTRY,
			CITY PORCITY,
			STATES PORSTATES,
			COUNTRY PORCOUNTRY,
			COMPANY MAINCARRIER,
			AIRPORTS PODAIR,
			AIRPORTS PORAIR
		WHERE RQI_RQBK_ID = RQSC_RQBK_ID
			AND RQBK_IDX.RQI_COMPLETE = -1    -- Completed only
			AND RQBK_IDX.RQI_ACTIVE = -1      -- Active only
			AND RQBK_IDX.RQI_RQBK = 2         -- Booking only (RateQuote=1, Booking=2)
			AND RQI_RQBK_ID = RQAC_RQBK_ID (+)
			AND RQI_RQBK_ID = RQOC_RQBK_ID (+)
			AND RQI_RQBK_ID = RQM_RQBK_ID (+)
			AND RQSC_SH_ID = SHIPPER.CO_ID (+)
			AND RQSC_CS_ID = CONSIGNEE.CO_ID (+)
			AND RQM_CO_ID = MAINCARRIER.CO_ID (+)
			AND RQSC_POD = PODCITY.CT_ID (+)
			AND RQSC_POR = PORCITY.CT_ID (+)
			AND RQSC_POD_AIR = PODAIR.AP_ID (+)
			AND RQSC_POR_AIR = PORAIR.AP_ID (+)
			AND PODCITY.CT_STATE_ID = PODSTATES.STATE_ID (+)
			AND PODCITY.CT_COUNTRY_ID = PODCOUNTRY.CY_ID (+)
			AND PORCITY.CT_STATE_ID = PORSTATES.STATE_ID (+) 
			AND PORCITY.CT_COUNTRY_ID = PORCOUNTRY.CY_ID (+)
			AND RQI_FCL_LCL = RQCT_ID (+)
			AND RQM_HAZ_PERISH = HPT_ID (+)
			AND DECODE(CompanyType, 1, SHIPPER.CO_ID, 2, CONSIGNEE.CO_ID) = CompanyID
		ORDER BY REQUEST_DATE DESC;
	END IF;

	EXCEPTION WHEN OTHERS THEN
		RAISE;
END;