create or replace PROCEDURE SP_PORTAL_TRACE_OCEAN
(
	I_HARBOUR_NUMBER IN VARCHAR2,
	O_CURSOR OUT SYS_REFCURSOR
)
AS

	V_CONTAINER_COUNT NUMBER;

BEGIN
	SELECT COUNT(*) INTO V_CONTAINER_COUNT
	FROM RQBK_FCL_HDR, RQBK_IDX
	WHERE RQBK_IDX.RQI_RQBK_ID = RQBK_FCL_HDR.RQFH_RQBK_ID
		AND RQI_RQBK_NUM = I_HARBOUR_NUMBER;

	OPEN O_CURSOR FOR
	SELECT DISTINCT
		RQOC_SHIPPER_CUTOFF SHIPPER_CUTOFF_DATE,
		RQOC_TERM_CUTOFF TERMINAL_CUTOFF_DATE,
		RQOC_PORT_CUTOFF PORT_CUTOFF_DATE,
		RQOC_SAIL_DATE SAIL_DATE,
		RQOC_ACT_SAIL_DATE ACTUAL_SAIL_DATE,
		RQOC_PORT_DISCHARGE_ARR_DATE PORT_DISCHARGE_DATE,
		RQOC_POD_ARR_DATE POD_ARRIVAL_DATE,
		RQOC_BK_NUM BOOKING_NUMBER,
		RQI_RQBK_NUM HARBOUR_NUMBER,
		--DECODE(RQI_FCL_LCL, 1, NULL, RQLH_TOT_PIECES) TOTAL_PIECES,
		--DECODE(RQI_FCL_LCL, 1, NULL, RQLH_TOT_LBS) TOTAL_WEIGHT,
		--DECODE(RQI_FCL_LCL, 1, NULL, RQLH_TOT_CUFT) TOTAL_VOLUME,
		--CONT_TYPE CONTAINER_TYPE,
		V_CONTAINER_COUNT CONTAINER_COUNT,
		COMPANY.CO_NAME COMPANY_NAME
	FROM
		RQBK_IDX, 
		RQBK_OC_CARRIER,
		RQBK_MC,
		RQBK_FCL_HDR,
		RQBK_LCL_HDR,
		COMPANY,
		CONTAINERS
	WHERE RQI_RQBK_NUM = I_HARBOUR_NUMBER
		AND RQI_RQBK_ID = RQOC_RQBK_ID (+)
		AND RQM_RQBK_ID = RQI_RQBK_ID
		AND CO_ID = RQM_CO_ID
		AND RQI_RQBK_ID = RQLH_RQBK_ID (+)
		AND RQI_RQBK_ID = RQFH_RQBK_ID (+)
		AND RQFH_CONT_CODE = CONT_ID (+);
	EXCEPTION WHEN OTHERS THEN
		RAISE;
END;